import asyncio
import os
from app.services.pyannote_service import PyannoteService
from app.services.llm_service import LLMService
from app.core.config import settings
# Helper to avoid import errors if supabase not installed (it is, but good practice)
try:
    from supabase import create_client, Client
except ImportError:
    pass

async def process_recording(file_path: str, meeting_id: str = None):
    """
    Run high-precision diarization on a completed meeting recording.
    Updates the 'meetings' table with transcript and MoM.
    """
    print(f"\n[Post-Processing] Starting analysis for: {file_path}")
    
    try:
        # Initialize Services
        pyannote_service = PyannoteService()
        llm_service = LLMService()
        
        # Diarization
        print("[Post-Processing] Running Pyannote Diarization...")
        loop = asyncio.get_event_loop()
        output = await loop.run_in_executor(None, lambda: pyannote_service.pipeline(file_path, return_embeddings=True))
        
        # Unpack tuple
        if isinstance(output, tuple):
             dia, embeddings = output
        else:
             dia = getattr(output, 'speaker_diarization', output)
             embeddings = getattr(output, 'speaker_embeddings', None)

        # Merge speakers
        dia = pyannote_service.merge_speakers(dia, embeddings)
        
        print(f"\n[Post-Processing] Analysis Complete! Found {len(dia.labels())} unique speakers.")
        
        # Format Transcript
        transcript_lines = []
        idx = 0
        for turn, _, _ in dia.itertracks(yield_label=True):
            # We are mimicking the logic from before but assuming we might want to attach text later?
            # Wait, Pyannote only gives timestamps/speakers. It DOES NOT give text.
            # The previous implementation said: "In a real production app, we would now: 1. Fetch the stored text transcript. 2. Re-align..."
            # CRITICAL: We don't have the WORDS here unless we stored them from ElevenLabs or run STT again.
            # The prompt implies: "store the transcripts generated post processing".
            # If we rely ONLY on Pyannote here, we lose the text generated by ElevenLabs during the live stream unless we saved it!
            
            # The previous 'ElevenLabsService' saved `full_audio_buffer`. It DID NOT allow retrieving the words from the live session easily unless it stored them.
            # BUT the user said "store the transcripts generated post processing". This usually implies running a high-quality STT (like Whisper) OR using the buffered text.
            
            # OPTION: Regurgitate the ElevenLabs live text? No, that was streamed.
            # OPTION: Run STT (Assembly / Whisper) here? 
            # Given I only have ElevenLabs configured (and removed AssemblyAI), and the user said "replace elevenlabs... actually no, use elevenlabs", 
            # I must assume either:
            # A) The user expects me to use ElevenLabs to transcribe the file again? (Costly/Slow?)
            # B) Or use a free/local STT?
            # C) Or maybe the "live_transcript" column should have been populated *during* the meeting, and here we just improve it?
            
            # However, `process_recording` takes a WAV file. Pyannote gives SPEAKERS. It does NOT give TEXT.
            # If I just save speaker segments, I have no text.
            # User said: "transcripts generated post processing".
            
            # I will assume I should use **Gemini** (since I have it now) or **ElevenLabs** to transribe the audio file?
            # ElevenLabs Scribe is STT. `elevenlabs_service.py` uses `self.client.speech_to_text.convert`.
            # I should reuse that!
            pass 

        # Let's perform STT on the full file using ElevenLabs (since we have the key and client)
        print("[Post-Processing] Running STT on full file...")
        from elevenlabs import ElevenLabs
        el_client = ElevenLabs(api_key=settings.ELEVENLABS_API_KEY)
        
        # Note: ElevenLabs STT can do diarization too. Maybe we don't even need Pyannote if EL does it well?
        # But user explicitly wanted Pyannote. So let's stick to the plan:
        # Actually, aligning Pyannote speakers with EL text is hard without word-level timestamps from EL matching perfectly.
        # EL Scribe returns words with timestamps. I can align them.
        
        with open(file_path, "rb") as f:
             audio_data = f.read()
             
        # Re-transcribe full file for best quality
        # We use a helper to get the transcript object
        transcript_obj = el_client.speech_to_text.convert(
            model_id="scribe_v1",
            file=audio_data, 
        )
        
        # If EL Scribe does diarization, we might just use that for the "text" and use Pyannote for "verification" or just overwrite?
        # The user seems to trust Pyannote for diarization.
        # Let's use EL to get words + times, and Pyannote to get speakers + times, and align.
        # Alignment logic: For each word, find the Pyannote segment that overlaps it.
        
        full_text_transcript = []
        
        # We need to parse transcript_obj. It likely resembles the partial event but for the whole file. 
        # Checking docs/previous usage... it returns a generator or object? 
        # In stream it was a generator. In convert (blocking) it might be an object.
        # Let's assume it returns an object with .words
        
        words = getattr(transcript_obj, 'words', [])
        
        # Simple alignment
        for word in words:
            start = word.start
            end = word.end
            text = word.text
            
            # Find speaker from Pyannote dia
            # We search for the segment with max overlap
            speaker = "Unknown"
            max_overlap = 0
            
            for turn, _, label in dia.itertracks(yield_label=True):
                 overlap_start = max(start, turn.start)
                 overlap_end = min(end, turn.end)
                 dur = overlap_end - overlap_start
                 if dur > max_overlap:
                     max_overlap = dur
                     speaker = label
            
            full_text_transcript.append(f"{speaker}: {text}")
            
        # Deduplicate speakers (combine consecutive words from same speaker)
        formatted_transcript = ""
        current_speaker = None
        current_block = []
        
        for item in full_text_transcript:
            spk, txt = item.split(": ", 1)
            if spk != current_speaker:
                if current_speaker:
                    formatted_transcript += f"**{current_speaker}**: {' '.join(current_block)}\n\n"
                current_speaker = spk
                current_block = [txt]
            else:
                current_block.append(txt)
        if current_speaker:
             formatted_transcript += f"**{current_speaker}**: {' '.join(current_block)}\n\n"
             
        print(f"[Post-Processing] Transcript generated ({len(formatted_transcript)} chars).")
        
        if meeting_id:
            await update_meeting_record(meeting_id, file_path, formatted_transcript, llm_service)
        else:
            print("[Post-Processing] No meeting_id provided. Skipping DB update.")
            print("Preview of Transcript:")
            print(formatted_transcript[:200] + "...")

    except Exception as e:
        print(f"[Post-Processing] Error: {e}")
        import traceback
        traceback.print_exc()

async def update_meeting_record(meeting_id: str, file_path: str, transcript: str, llm_service: LLMService):
    url: str = settings.SUPABASE_URL
    key: str = settings.SUPABASE_ANON_KEY
    supabase: Client = create_client(url, key)
    
    print(f"[Supabase] Updating Meeting {meeting_id}...")
    
    # 1. Update Live Transcript
    # We might also want to upload the recording and save URL? user didn't explicitly ask for recording_url in 'meetings' schema, 
    # but mentioned selfie_url.
    # The schema has 'voice_input_notes', 'live_transcript', 'mom'. 
    # Let's stick to updating 'live_transcript'.
    
    supabase.table("meetings").update({
        "live_transcript": transcript,
        "status": "processing_mom"
    }).eq("id", meeting_id).execute()
    
    # 2. Fetch Notes
    print("[Supabase] Fetching notes for context...")
    response = supabase.table("meetings").select("voice_input_notes").eq("id", meeting_id).execute()
    notes = ""
    if response.data and len(response.data) > 0:
        notes = response.data[0].get("voice_input_notes", "")
        
    # 3. Generate MoM
    print("[Post-Processing] Generating MoM with LLM...")
    mom = await llm_service.generate_mom(transcript, notes)
    print(f"[Post-Processing] MoM Generated: \n{mom}")
    
    # 4. Update MoM
    supabase.table("meetings").update({
        "mom": mom,
        "status": "completed"
    }).eq("id", meeting_id).execute()
    
    print("[Supabase] Meeting updated successfully.")

# Note: ElevenLabs call in process_recording assumes the input file format.
# If converting file to bytes for EL, ensure correct reading.
